### ISSUE TITLE
RigidBodyTreeInspector Build Issue

### ISSUE THREAD

**Issue by nddoshi** [rdeits/RigidBodyTreeInspector.jl#17]
Hey, 

I downloaded Julia 0.5.1-xenial1, and I've added the RigidBodyDynamics package. When I try to add the RigidBodyTreeInspector package, I get the error below.  The specific command I ran there was Pkg.build("RigidBodyTreeInspector"). I believe I have python 2.7.12. 
![screenshot from 2017-03-27 19-24-18](https://cloud.githubusercontent.com/assets/2799968/24382248/ff97dbdc-1322-11e7-9cdd-03f5ffc2d26c.png)

**Comment by rdeits** [comment]
I'm afraid you're running into https://github.com/JuliaLang/BinDeps.jl/issues/199

Can you please try installing those apt packages manually? 

```
sudo apt-get install python-dev libvtk5-qt4-dev python-vtk
```

and then re-run `Pkg.build("DrakeVisualizer")` in Julia

**Comment by nddoshi** [comment]
thanks! that seemed to work. I also had to install glib manually (`sudo apt-get install libglib2.0-dev
`). I'll try tout some of the examples and let you know how it goes.

**Comment by nddoshi** [comment]
One more quick question -- I can put this on a separate thread since it's off topic. I tried running the first few cells in demo.ipynb using jupyter notebook. It works well until I try to run: `RigidBodyTreeInspector.inspect(mechanism; show_inertias=false, randomize_colors=true)`
I see the robot in the visualizer, but none of the sliders appear in my notebook. 

Also, when I run the next set of commands, I get the following error when it try to run:
`configurations[i] = copy(configuration(state))`
![screenshot from 2017-03-28 12-21-53](https://cloud.githubusercontent.com/assets/2799968/24415965/25c1d3ec-13b1-11e7-8e40-cbce1755be28.png)

**Comment by rdeits** [comment]
For the sake of my sanity, I've split these off into #18 and #19

By the way, when you're posting error messages like this, it's better to post the text of the error rather than a screenshot, since the text will be searchable in the future when someone else has the same problem. Just put triple backticks around the text so github doesn't try to format it: https://help.github.com/articles/creating-and-highlighting-code-blocks/#fenced-code-blocks

**Comment by nddoshi** [comment]
Noted. Will do that in the future, thanks!
