### ISSUE TITLE
Missing configuration() method

### ISSUE THREAD

**Issue by rdeits** [rdeits/RigidBodyTreeInspector.jl#18]
From @neeld over in #17 

> Also, when I run the next set of commands, I get the following error when it try to run:
configurations[i] = copy(configuration(state))

![](https://cloud.githubusercontent.com/assets/2799968/24415965/25c1d3ec-13b1-11e7-8e40-cbce1755be28.png)

Sorry, that's my fault: RigidBodyDynamics was updated to v0.1.0 a few days ago, and I haven't tagged a new release of RigidBodyTreeInspector yet. Can you please try:

```julia
Pkg.checkout("RigidBodyTreeInspector")
Pkg.checkout("RigidBodyDynamics")
```

which will bring you up to the master version. You'll have to restart your Jupyter notebook for the updated package to take effect.

**Comment by nddoshi** [comment]
Yeah, this seems to work fine now, thanks!

**Comment by rdeits** [comment]
New tagged version coming soon: https://github.com/JuliaLang/METADATA.jl/pull/8547

**Comment by tkoolen** [comment]
Close this?

**Comment by nddoshi** [comment]
fine with me


-- 
Neel Doshi
PhD Candidate in Electrical Engineering
John A Paulson School of Engineering and Applied Sciences
Harvard University
