### ISSUE TITLE
No sliders when running `inspect()`

### ISSUE THREAD

**Issue by rdeits** [rdeits/RigidBodyTreeInspector.jl#19]
From @neeld over in #17 

> I tried running the first few cells in demo.ipynb using jupyter notebook. It works well until I try to run: RigidBodyTreeInspector.inspect(mechanism; show_inertias=false, randomize_colors=true)
I see the robot in the visualizer, but none of the sliders appear in my notebook.

That might be a general issue with Interact.jl. Can you please try this (in a Jupyter notebook):

```julia
using Interact
@manipulate for i in 1:10
  i
end
```

You should see a slider in the notebook, and it should update the printed value of `i` as you move it. Does that work? 

If not, can you please try:

```julia
Pkg.build("Interact")
```

and then re-starting jupyter.

**Comment by nddoshi** [comment]
Unfortunately I don't see a slider. All I get is: ```Out[2]: 5```. Though I did see the following when I built interact: 
```Pkg.build("Interact")
INFO: Building Interact
INFO: Enabling widgetsnbextension
Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK
INFO: ipywidgets version found: 6.0.0
INFO: A compatible version of ipywidgets was found. All good.
```

**Comment by rdeits** [comment]
Ok, then it's definitely an Interact.jl or IJulia.jl issue. And you've tried restarting the whole jupyter server? Can you also try `Pkg.build("IJulia")`

**Comment by nddoshi** [comment]
By restarting the whole server, do you just mean killing the process in the terminal where I ran `julia notebook` and starting it again? If so, yes. I also tried `Pkg.build("IJulia")`. Unfortunately, I still get the same result as above. I have Jupyter version 4.3.0 if that helps. Also running this on the default firefox with 16.04 LTS

**Comment by rdeits** [comment]
Yeah, that's exactly right. Ok, thanks for trying all of that. We'll just have to dig a little deeper. Can you please show me the output of `versioninfo()` and `Pkg.status()` in Julia? 

And can you please try:

* start jupyter from terminal
* create a new jupyter notebook
* open the developer console in your browser (ctrl+shift+i in chrome, then click on "console")
* run `using Interact` and that `@manipulate for...` code from above
* see if there are any errors or warnings in the javascript console

**Comment by nddoshi** [comment]
No problem! Thanks for your help. Here's what I get when I run `versioninfo()`
```
Julia Version 0.5.1
Commit 6445c82 (2017-03-05 13:25 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell) 
```

And here's what I get when I run `Pkg.status()`

```6 required packages:
 - Gadfly                        0.6.0
 - IJulia                        1.4.1+             master
 - Interact                      0.4.3+             master
 - PyCall                        1.11.0
 - RigidBodyDynamics             0.1.0+             master
 - RigidBodyTreeInspector        0.1.0+             master
64 additional packages:
 - AxisAlgorithms                0.1.6
 - BinDeps                       0.4.7
 - CMakeWrapper                  0.0.2
 - Calculus                      0.2.2
 - ColorTypes                    0.3.5
 - Colors                        0.7.3
 - Compat                        0.21.0
 - Compose                       0.4.5
 - Conda                         0.5.2
 - Contour                       0.2.0
 - CoordinateTransformations     0.4.0
 - DataArrays                    0.3.12
 - DataFrames                    0.9.0
 - DataStructures                0.5.3
 - DiffBase                      0.1.0
 - Distances                     0.4.1
 - Distributions                 0.12.2
 - DocStringExtensions           0.3.2
 - DrakeVisualizer               0.1.3
 - DualNumbers                   0.3.0
 - FileIO                        0.3.1
 - FixedPointNumbers             0.3.5
 - FixedSizeArrays               0.2.5
 - ForwardDiff                   0.4.1
 - GZip                          0.3.0
 - GeometryTypes                 0.2.2
 - Hexagons                      0.0.4
 - Hiccup                        0.1.1
 - Interpolations                0.3.8
 - Iterators                     0.3.0
 - JSON                          0.8.3
 - Juno                          0.2.7
 - KernelDensity                 0.3.2
 - LCMCore                       0.0.3
 - LightXML                      0.4.0
 - LineSearches                  0.1.5
 - Loess                         0.1.0
 - MacroTools                    0.3.6
 - MbedTLS                       0.4.5
 - Measures                      0.0.3
 - Media                         0.2.6
 - MeshIO                        0.0.6
 - Meshing                       0.0.3
 - NaNMath                       0.2.4
 - Optim                         0.7.8
 - PDMats                        0.5.6
 - Parameters                    0.7.2
 - PositiveFactorizations        0.0.4
 - QuadGK                        0.1.1
 - Ratios                        0.0.4
 - Reactive                      0.3.7
 - Reexport                      0.0.3
 - Rmath                         0.1.6
 - Rotations                     0.3.5
 - SHA                           0.3.2
 - Showoff                       0.0.7
 - SortingAlgorithms             0.1.1
 - SpecialFunctions              0.1.1
 - StaticArrays                  0.3.0
 - StatsBase                     0.13.1
 - StatsFuns                     0.4.0
 - URIParser                     0.1.8
 - WoodburyMatrices              0.2.2
 - ZMQ                           0.4.2
```
And finally, there are a bunch of errors when I run that code (essentially saying jupyter.widget can't be found). I've copied the full text below: 

```Could not open comm  --  Error: Class jupyter.widget not found in registry 
Stack trace:
load_class/<@http://localhost:8888/static/notebook/js/main.min.js?v=51e81021865aa858b5b5af6e931a27c5:13155:28
load_class@http://localhost:8888/static/notebook/js/main.min.js?v=51e81021865aa858b5b5af6e931a27c5:13140:16
CommManager.prototype.comm_open@http://localhost:8888/static/notebook/js/main.min.js?v=51e81021865aa858b5b5af6e931a27c5:22383:31
.proxy/i@http://localhost:8888/static/notebook/js/main.min.js?v=51e81021865aa858b5b5af6e931a27c5:87:5486
Kernel.prototype._handle_iopub_message@http://localhost:8888/static/notebook/js/main.min.js?v=51e81021865aa858b5b5af6e931a27c5:23786:20
Kernel.prototype._finish_ws_message@http://localhost:8888/static/notebook/js/main.min.js?v=51e81021865aa858b5b5af6e931a27c5:23622:24
Kernel.prototype._handle_ws_message/this._msg_queue<@http://localhost:8888/static/notebook/js/main.min.js?v=51e81021865aa858b5b5af6e931a27c5:23613:39
  main.min.js:13191:17
Couldn't process kernel message Object { fileName: "http://localhost:8888/static/notebo…", lineNumber: 13110, columnNumber: 19, message: "Could not open comm", error_stack: Array[2], stack: "" }  main.min.js:23614:34
Couldn't process kernel message Object { fileName: "http://localhost:8888/static/notebo…", lineNumber: 13110, columnNumber: 19, message: "Could not open comm", error_stack: Array[2], stack: "" }  main.min.js:23614:34
Couldn't process kernel message Object { fileName: "http://localhost:8888/static/notebo…", lineNumber: 13110, columnNumber: 19, message: "Could not open comm", error_stack: Array[2], stack: "" }  main.min.js:23614:34```

**Comment by rdeits** [comment]
That's very strange. Ok, let's try another approach. You're currently using the jupyter notebook provided by your system's install of `python` and `ipython`. That *should* be working, but it isn't. Fortunately, there's a way to have Julia build a self-contained version of the notebook that should be more compatible. Can you please try the following:

* shut down all your jupyter terminal sessions
* open julia, and run:
  * `ENV["PYTHON"] = ""`
  * `Pkg.build("PyCall")`
  * `Pkg.build("IJulia")`
  * `Pkg.build("Interact")`
  * `using IJulia`
  * `notebook(dir=pwd())`

And then try creating a new notebook and running `@manipulate` again.

**Comment by rdeits** [comment]
If that works, then instead of running `jupyter notebook` you'll want to launch it from Julia. You can do that in one line with:

```
julia -e "using IJulia; notebook(dir=pwd())"
```

**Comment by nddoshi** [comment]
That fixed the issue, I see sliders now. Do you think I'm using an outdated version of python. I think I'm still using python 2, and so I installed the version of jupyter compatible with that, using the commands: 

```
pip install --upgrade pip
pip install jupyter 
```

**Comment by rdeits** [comment]
Python2 should be fine (I'm still using it for a few projects). It's possible that your `ipython` version was out of date, though. Perhaps `pip install --upgrade ipython` and `pip install --upgrade jupyter`?

**Comment by nddoshi** [comment]
Those both seem up to date. Don't worry about it for now, seems to be working fine! I appreciate your help

**Comment by rdeits** [comment]
Ok, great! I'll close this, but feel free to open a new issue if you have more trouble.
