### ISSUE TITLE
Better support for Mechanisms with loops

### ISSUE THREAD

**Issue by tkoolen** [rdeits/RigidBodyTreeInspector.jl#21]
Loop joints are currently not handled in the generation of geometry for a `Mechanism`. 

Here are two proposed ways to improve this situation:

Let `f(body, joint)` be the frame associated with a joint (either frame before or frame after) that is rigidly fixed to the body.

First version:
```
for each body
    for each joint attached to body
        create a cylinder between the origin of f(body, joint) and the body's default frame
    end
end
```

```
for each body
    for each pair (j1, j2) of joints attached to body, with j1 != j2
        create a cylinder between the origins of f(body, j1) and f(body, j2)
    end
end
```

@rdeits, which one do you prefer? I kind of like the second better.

**Comment by tkoolen** [comment]
Bump.

**Comment by rdeits** [comment]
Yeah, I also think the second sounds better, since a preference for the body's default frame doesn't really make sense for systems with loops. Option 2 should still give the same appearance for tree mechanisms, right?

**Comment by tkoolen** [comment]
Yep, that's why I like it too. Alright, I'll implement that then.
