### ISSUE TITLE
Can't parse leading whitespace in vectors

### ISSUE THREAD

**Issue by goretkin** [rdeits/RigidBodyTreeInspector.jl#32]
Vectors with leading/trailing whitespace occurs in [some URDFs](https://github.com/RobotLocomotion/drake/blob/4345f4fba23a0c331c11cb80872b94b568e77e6d/drake/examples/PR2/pr2.urdf#L825)

And the `parse_vector` function can't handle this whitespace.  Wrapping the string in `strip` would accept more URDFs as valid, with I think no downside.

```
LightXML.root(LightXML.parse_string("""<origin rpy="0 0 0 " xyz="0 0 0.0"/>""")) |> 
    a -> RigidBodyTreeInspector.parse_vector(Float64, a, "rpy", "0 0 0")

MethodError: Cannot `convert` an object of type Void to an object of type Float64
This may have arisen from a call to the constructor Float64(...),
since type constructors fall back to convert methods.
```

@tkoolen I think there's the same issue in RigidBodyDynamics

**Comment by rdeits** [comment]
Calling `strip()` seems totally reasonable to me

**Comment by goretkin** [comment]
I'm in the middle of submitting a PR

**Comment by tkoolen** [comment]
Yeah, there's some code duplication between RigidBodyTreeInspector and RigidBodyDynamics URDF parsing unfortunately. I'll fix it in RBD. @rdeits, should we reduce the code duplication?

**Comment by rdeits** [comment]
Yeah, we probably should. I don't think it's a huge problem right now, though.
