### ISSUE TITLE
Unfortunate Valkyrie head situation

### ISSUE THREAD

**Issue by tkoolen** [rdeits/RigidBodyTreeInspector.jl#35]
![image](https://user-images.githubusercontent.com/2585880/29030913-8db5f864-7b5a-11e7-84a7-5b2e295b2348.png)

Code to reproduce:
```julia
# Pkg.checkout("RigidBodyDynamics")
# Pkg.clone("https://github.com/tkoolen/ValkyrieRobot.jl.git")

using RigidBodyDynamics
using RigidBodyTreeInspector
using ValkyrieRobot

val = Valkyrie()
mechanism = val.mechanism;

DrakeVisualizer.any_open_windows() || DrakeVisualizer.new_window(); sleep(1)
vis = Visualizer()[:valkyrie]
setgeometry!(vis, mechanism, parse_urdf(ValkyrieRobot.urdfpath(), mechanism; package_path = [ValkyrieRobot.packagepath()]))
remove_fixed_tree_joints!(mechanism)

state = MechanismState{Float64}(mechanism)
settransform!(vis, state)
```

This is due to the `remove_fixed_tree_joints!` call. This used to work. Other mechanism modifications (like rerooting) result in similar issues. I'll take a look at this soon, but just wanted to report it for now.

**Comment by rdeits** [comment]
Whoops, thanks for noticing this 😄

**Comment by rdeits** [comment]
We realized that the problem goes away if you call `setgeometry()` *after* modifying the mechanism, which I think is an OK workaround.
